# Generated by Django 6.0.7 on 2026-07-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, null=True, unique=True)),
                ('order_date', models.DateField(null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('amount', models.FloatField(default=0.0, null=True)),
                ('gst', models.FloatField(default=0.0, null=True)),
                ('bill_amount', models.FloatField(default=0.0, null=True)),
                ('customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.customer')),
                ('product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.product')),
            ],
        ),
    ]
